version: "3.3"

networks:
  nginx_network:
    driver: bridge

volumes:
  django_socket:
    driver: local


services:
  app:  # 実際のWebアプリケーションを起動するコンテナ
    restart: always
    build: .
    command: gunicorn project.wsgi:application --config guniconf.py
    volumes:
      - django_socket:/var/www/app/tmp/sockets
      - .:/var/www/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: app_db_development
      DB_USER: deploy
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  redis:  # ジョブを非同期で動かすために必要
    image: redis
    ports:
      - 6379:6379
    volumes:
      - .docker/redis/data:/data

  nginx:  # プロキシサーバー
    restart: always
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - django_socket:/var/www/app/tmp/sockets
      - .docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - nginx_network

  db: # データベース用サーバー(Postgresql使用)
    restart: always
    image: postgres:10.4
    ports:
      - 5432:5432
    volumes:
      - .docker/db/data:/var/lib/postgresql/data
      - .docker/db/initializers:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: ${DB_PASSWORD}

